modeller_order = [
    'Enclosure',
    'Controller',
    'VirtualDisk',
    'PowerSupply',
    'HardDisk',
    'Volume',
    'HostPort',
    'ExpansionPort',
    'ManagementPort',
    'InoutModule',
    'CompactFlash'
    ]

'''
May be not usefull in future!!!

statistic_map = [
    'Controller',
    'Disk',
    'HostPort',
    'Volume',
    'Virtualdisk',
]
'''
device_map = {
    'Enclosure': {
        'relname': 'enclosures',
        'modname': 'ZenPacks.community.HPMSA.Enclosure',
        'compname': None,
        'xml_obj_command': 'enclosures',
        'xml_obj_filter': "./OBJECT[@basetype='enclosures']",
        'xml_obj_id': 'enclosure-id',
        'xml_obj_title': 'durable-id',
        'xml_obj_relation': None,
        'xml_obj_relation_pattern': None,
        'xml_obj_attributes': ['enclosure-wwn', 'description'],
        },
    'PowerSupply': {
        'relname': 'powerSupplys',
        'modname': 'ZenPacks.community.HPMSA.PowerSupply',
        'compname': 'enclosures/',
        'xml_obj_command': 'power-supplies',
        'xml_obj_filter': "./OBJECT[@name='power-supplies']",
        'xml_obj_id': 'durable-id',
        'xml_obj_title': 'durable-id',
        'xml_obj_relation': 'location',
        'xml_obj_relation_pattern': 'Enclosure ([0-9])',
        'xml_obj_attributes': [],
        },
    'Controller': {
        'relname': 'controllers',
        'modname': 'ZenPacks.community.HPMSA.Controller',
        'compname': None,
        'xml_obj_command': 'controllers',
        'xml_obj_filter': "./OBJECT[@basetype='controllers']",
        'xml_obj_id': 'controller-id',
        'xml_obj_title': 'durable-id',
        'xml_obj_relation': None,
        'xml_obj_relation_pattern': None,
        'xml_obj_attributes': ['node-wwn', 'description'],
        'xml_stat_command': 'controller-statistics',
        'xml_stat_filter': "./OBJECT[@basetype='controller-statistics']",
        'xml_stat_id': 'durable-id',
        'xml_stat_id_pattern': 'controller_([A-Z])',
        },
    'HardDisk': {
        'relname': 'hardDisks',
        'modname': 'ZenPacks.community.HPMSA.HardDisk',
        'compname': 'enclosures/',
        'xml_obj_command': 'disks',
        'xml_obj_filter': "./OBJECT[@name='drive']",
        'xml_obj_id': 'durable-id',
        'xml_obj_title': 'durable-id',
        'xml_obj_relation': 'enclosure-id',
        'xml_obj_relation_pattern': None,
        'xml_obj_attributes': ['size', 'usage'],
        'xml_stat_command': 'disk-statistics',
        'xml_stat_filter': "./OBJECT[@basetype='disk-statistics']",
        'xml_stat_id': 'durable-id',
        'xml_stat_id_pattern': None,
        },
    'HostPort': {
        'relname': 'hostPorts',
        'modname': 'ZenPacks.community.HPMSA.HostPort',
        'compname': 'controllers/',
        'xml_obj_command': 'ports',
        'xml_obj_filter': "./OBJECT[@basetype='port']",
        'xml_obj_id': 'durable-id',
        'xml_obj_title': 'durable-id',
        'xml_obj_relation': 'controller',
        'xml_obj_relation_pattern': None,
        'xml_obj_attributes': ['port-type', 'actual-speed'],
        'xml_stat_command': 'host-port-statistics',
        'xml_stat_filter': "./OBJECT[@basetype='host-port-statistics']",
        'xml_stat_id': 'durable-id',
        'xml_stat_id_pattern': None,
        },
    'ExpansionPort': {
        'relname': 'expansionPorts',
        'modname': 'ZenPacks.community.HPMSA.ExpansionPort',
        'compname': 'enclosures/',
        'xml_obj_command': 'sas-link-health',
        'xml_obj_filter': "./OBJECT[@basetype='expander-ports']",
        'xml_obj_id': 'durable-id',
        'xml_obj_title': 'durable-id',
        'xml_obj_relation': 'enclosure-id',
        'xml_obj_relation_pattern': None,
        'xml_obj_attributes': [],
        },
    'ManagementPort': {
        'relname': 'managementPorts',
        'modname': 'ZenPacks.community.HPMSA.ManagementPort',
        'compname': 'controllers/',
        'xml_obj_command': 'controllers',
        'xml_obj_filter': "./OBJECT[@basetype='controllers']/OBJECT[@basetype='network-parameters']",
        'xml_obj_id': 'durable-id',
        'xml_obj_title': 'durable-id',
        'xml_obj_relation': 'durable-id',
        'xml_obj_relation_pattern': 'mgmtport_([a-z])',
        'xml_obj_attributes': ['link-speed', 'ip-address'],
        },
    'InoutModule': {
        'relname': 'inoutModules',
        'modname': 'ZenPacks.community.HPMSA.InoutModule',
        'compname': 'enclosures/',
        'xml_obj_command': 'enclosures',
        'xml_obj_filter': "./OBJECT[@basetype='enclosures']/OBJECT[@basetype='io-modules']",
        'xml_obj_id': 'durable-id',
        'xml_obj_title': 'durable-id',
        'xml_obj_relation': 'durable-id',
        'xml_obj_relation_pattern': 'iom_([1-9])',
        'xml_obj_attributes': ['description'],
        },
    'CompactFlash': {
        'relname': 'compactFlashs',
        'modname': 'ZenPacks.community.HPMSA.CompactFlash',
        'compname': 'controllers/',
        'xml_obj_command': 'controllers',
        'xml_obj_filter': "./OBJECT[@basetype='controllers']/OBJECT[@basetype='compact-flash']",
        'xml_obj_id': 'durable-id',
        'xml_obj_title': 'name',
        'xml_obj_relation': 'controller-id',
        'xml_obj_relation_pattern': None,
        'xml_obj_attributes': ['cache-flush'],
        },
    'VirtualDisk': {
        'relname': 'virtualDisks',
        'modname': 'ZenPacks.community.HPMSA.VirtualDisk',
        'compname': None,
        'xml_obj_command': 'vdisks',
        'xml_obj_filter': "./OBJECT[@basetype='virtual-disks']",
        'xml_obj_id': 'name',
        'xml_obj_title': 'name',
        'xml_obj_relation': None,
        'xml_obj_relation_pattern': None,
        'xml_obj_attributes': ['size', 'raidtype'],
        'xml_stat_command': 'vdisk-statistics',
        'xml_stat_filter': "./OBJECT[@basetype='vdisk-statistics']",
        'xml_stat_id': 'name',
        'xml_stat_id_pattern': None,
        },
    'Volume': {
        'relname': 'volumes',
        'modname': 'ZenPacks.community.HPMSA.Volume',
        'compname': None,
        'xml_obj_command': 'volumes',
        'xml_obj_filter': "./OBJECT[@basetype='volumes']",
        'xml_obj_id': 'volume-name',
        'xml_obj_title': 'volume-name',
        'xml_obj_relation': None,
        'xml_obj_relation_pattern': None,
        'xml_obj_attributes': ['size', 'owner'],
        'xml_stat_command': 'volume-statistics',
        'xml_stat_filter': "./OBJECT[@basetype='volume-statistics']",
        'xml_stat_id': 'volume-name',
        'xml_stat_id_pattern': None,
        },
    }
